### ISSUE TITLE
1.20.4 fabric crafting recipes

### ISSUE THREAD

**Issue by EfficientStinkbug** [MarkusBordihn/BOs-Fire-Extinguisher#4]
The recipes don't show up in the crafting table. Is there any way to include them? So far I haven't figured out how to craft anything

**Comment by MarkusBordihn** [comment]
Thanks for the feedback.
I will add the needed advancements to unlock the crafting recipes as soon a ingredient is in the inventory.

In the mean time you can use https://github.com/MarkusBordihn/BOs-Fire-Extinguisher/wiki which includes the crafting recipe for each single item.

**Comment by EfficientStinkbug** [comment]
Oh thank you, that helps! Really great mod btw!
