### ISSUE TITLE
1.19.2 Fire Extinguisher cannot extinguish nearby fire

### ISSUE THREAD

**Issue by Raaay-Fung** [MarkusBordihn/BOs-Fire-Extinguisher#5]
On version 1.19.2, the item fire extinguisher can only extinguish fires that are directly pointed at and no nearby fires are put out
Changing the radius to 8 also doesn't fix the problem

I got this when using only this mod so it should not be a compatibility issue

**Comment by MarkusBordihn** [comment]
Could you please let me know which version you are using like Fabric or Forge ?

**Comment by Raaay-Fung** [comment]
It was on forge 43.4.2 with mod version 6.3.0
