### ISSUE TITLE
Chinese translations submission

### ISSUE THREAD

**Issue by Raaay-Fung** [MarkusBordihn/BOs-Fire-Extinguisher#6]
I made some Chinese translations for the mod:
https://drive.google.com/drive/folders/1uA9NP6icW8FGs1OV-yiEqtbWgOhrIwQI?usp=sharing

**Comment by MarkusBordihn** [comment]
Thanks for this. Please create a "fork" of this repro and a corresponding "pull request" for the translation.

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by MarkusBordihn** [comment]
Related to #8.
