### ISSUE TITLE
Cant Craft The Fire Extinguisher

### ISSUE THREAD

**Issue by danieltudor9** [MarkusBordihn/BOs-Fire-Extinguisher#9]
**Describe the bug**
Cant craft it, cant open it in JEI, cant craft it using the github recipe.

**To Reproduce**
It just happens.

**Expected behavior**
Be able to craft and use it.

**Screenshots**
![2024-08-09_14 30 37](https://github.com/user-attachments/assets/e7e48d73-ea32-40d5-9ffb-b277fe331519)

**Debugging**
There was no crash, all good.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
It happens even with all other mods disabled.
![2024-08-09_14 44 25](https://github.com/user-attachments/assets/bf5719b2-ec35-4f78-b649-7555fb39588d)

**Additional context**
Nah, but the recipe for the signs looks mad expensive given you need to use an extinguisher for it, maybe some red+white dye and a sign would be better

**Comment by MarkusBordihn** [comment]
Thank you for your feedback! 
Could you please provide more details on the version of the mod you’re using and your Minecraft version?

I wasn’t able to reproduce the issue in version 1.18.2.

![image](https://github.com/user-attachments/assets/f79417b3-179e-43b8-9ba8-0f2a7e06763b)

**Comment by danieltudor9** [comment]
Hello!

I was using Minecraft 1.21, sadly i dont remember what mod version it was, but i was up to date on the date i submitted this.
